#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 21:03:18 2020

@author: joseguerra
"""


class PruebaA():
    value1 = 0
    value2 = 0
    
    
    def __init__(self, _value1, _value2):
        self.value1 = _value1
        self.value2 = _value2
        
        
class PruebaB():
    
    def probandoA(self,PruebaA):
        self.res = []
        self.res.append([PruebaA.value1, PruebaA.value2])
        return self.res
    

A = PruebaA(1,2)
B = PruebaB()

#A.init_value(1, 2)

print(A.value1)
print(B.probandoA(A))
    